"""Add privacy column to personal_posts

Revision ID: 503a632bd0e6
Revises: b907d8ba16c8
Create Date: 2025-07-25 17:14:24.250202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503a632bd0e6'
down_revision: Union[str, Sequence[str], None] = 'b907d8ba16c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_posts', sa.Column('privacy', sa.String(), nullable=False, server_default='friends_only'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal_posts', 'privacy')
    # ### end Alembic commands ###
