"""fix tables

Revision ID: 8d9619e1b94c
Revises: 1d6f94e8cdf8
Create Date: 2025-08-31 13:00:39.009393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d9619e1b94c'
down_revision: Union[str, Sequence[str], None] = '1d6f94e8cdf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    op.drop_table('creator_post_interactions')
    op.drop_table('friend_requests')
    op.drop_table('follows')
    op.drop_index(op.f('ix_feed_preferences_user_cat_tag'), table_name='feed_preferences')
    op.drop_table('feed_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_preferences',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('feed_preferences_category_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('feed_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name=op.f('feed_preferences_pkey'))
    )
    op.create_index(op.f('ix_feed_preferences_user_cat_tag'), 'feed_preferences', ['user_id', 'category_id'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('follows_follower_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name=op.f('follows_following_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('follows_pkey')),
    sa.UniqueConstraint('follower_id', 'following_id', name=op.f('follows_follower_id_following_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('friend_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('to_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name=op.f('friend_requests_from_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], name=op.f('friend_requests_to_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('friend_requests_pkey')),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name=op.f('friend_requests_from_user_id_to_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('creator_post_interactions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_interacted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['creator_posts.id'], name=op.f('creator_post_interactions_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('creator_post_interactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('creator_post_interactions_pkey'))
    )
    op.create_table('friends',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('friend_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name=op.f('friends_friend_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('friends_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('friends_pkey')),
    sa.UniqueConstraint('user_id', 'friend_id', name=op.f('friends_user_id_friend_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
