"""Add media_type to post_media

Revision ID: b907d8ba16c8
Revises: 18f318597264
Create Date: 2025-07-25 14:40:43.194252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b907d8ba16c8'
down_revision: Union[str, Sequence[str], None] = '18f318597264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('media_type', sa.String(), nullable=False))
    op.drop_column('post_media', 'post_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_media', sa.Column('post_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('post_media', 'media_type')
    # ### end Alembic commands ###
