from typing import Protocol
from uuid import UUID

from .users import User


class SocialService(Protocol):
    def follow(self, user_id: UUID, target_id: UUID) -> None: ...

    def unfollow(self, user_id: UUID, target_id: UUID) -> None: ...

    def send_friend_request(self, from_user_id: UUID, to_user_id: UUID) -> None: ...

    def cancel_friend_request(self, from_user_id: UUID, to_user_id: UUID) -> None: ...

    def accept_friend_request(self, from_user_id: UUID, to_user_id: UUID) -> None: ...

    def decline_friend_request(self, from_user_id: UUID, to_user_id: UUID) -> None: ...

    def get_followers(self, user_id: UUID) -> list[User]: ...

    def get_following(self, user_id: UUID) -> list[User]: ...

    def get_incoming_friend_requests(self, user_id: UUID) -> list[User]: ...

    def get_friends(self, user_id: UUID) -> list[User]: ...
